steps:
  - label: ':hammer: Tests'
    command: 'bundle exec fastlane test'
    artifact_paths:
      - app/build/test-results/**/*
    plugins:
      docker-compose#v2.3.0:
        run: app
  - label: ':rubocop: Lint'
    command: 'bundle exec fastlane lint'
    artifact_paths:
      - "app/build/reports/lint-results.html"
    plugins:
      docker-compose#v2.3.0:
        run: app
