# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

default_platform(:android)

platform :android do

  before_all do
    bundle_install
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean test")
  end

  desc "Run lint"
  lane :lint do
    gradle(task: "clean lint")
  end
end
